import { BASE_SPEED, COIN_VALUE, MAX_SPEED, METERS_PER_UNIT, RAMP_TIME } from "@/lib/game-config";

/* Leaderboard types and validation shared by the browser and the API routes. */

export const NAME_MAX_LENGTH = 16;
export const LEADERBOARD_SIZE = 10;
/** Longest run the server accepts (a run that long is already absurd). */
export const MAX_RUN_MS = 6 * 60 * 60 * 1000;

export interface RunStats {
  score: number;
  /** metres, as shown on the game-over screen */
  distance: number;
  coins: number;
  durationMs: number;
}

export interface SubmitRequest extends RunStats {
  playerId: string;
  name: string;
  token: string;
}

export interface LeaderboardEntry {
  rank: number;
  name: string;
  score: number;
  distance: number;
  coins: number;
  at: number;
  /** true for the player who asked (player ids are never sent to other players) */
  you: boolean;
}

export interface LeaderboardResponse {
  enabled: boolean;
  entries: LeaderboardEntry[];
  you: { rank: number; score: number } | null;
  error?: ApiError;
}

export type ApiError =
  | "bad_request"
  | "invalid_name"
  | "invalid_player"
  | "implausible_run"
  | "invalid_token"
  | "token_expired"
  | "token_used"
  | "rate_limited"
  | "store_unavailable"
  | "disabled";

export type SubmitResponse =
  | { ok: true; improved: boolean; best: number; rank: number }
  | { ok: false; error: ApiError };

export type RenameResponse = { ok: true; renamed: boolean } | { ok: false; error: ApiError };

export type TokenResponse = { enabled: true; token: string } | { enabled: false };

/**
 * Normalises a display name: NFC (so Vietnamese diacritics stay single characters),
 * letters / digits / space / `._-` only, collapsed whitespace, at most 16 characters.
 * Returns null when nothing usable is left.
 */
export function sanitizeName(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const cleaned = raw
    .normalize("NFC")
    .replace(/\s+/g, " ")
    .replace(/[^\p{L}\p{M}\p{N} ._-]/gu, "")
    .replace(/ {2,}/g, " ")
    .trim();
  const name = Array.from(cleaned).slice(0, NAME_MAX_LENGTH).join("").trim();
  return /[\p{L}\p{N}]/u.test(name) ? name : null;
}

/** Player ids are 128-bit random hex strings generated by the browser. */
export function isPlayerId(value: unknown): value is string {
  return typeof value === "string" && /^[a-f0-9]{32}$/.test(value);
}

/**
 * Farthest a run of the given length can possibly go, in metres: the integral of
 * the speed ramp `BASE + (MAX - BASE) * (1 - e^(-t / RAMP))`.
 */
export function maxMetersForDuration(durationMs: number): number {
  const t = Math.max(0, durationMs) / 1000;
  const units =
    MAX_SPEED * t - (MAX_SPEED - BASE_SPEED) * RAMP_TIME * (1 - Math.exp(-t / RAMP_TIME));
  return units * METERS_PER_UNIT;
}

/**
 * Sanity checks a submitted run against the game's rules. It can't make a
 * browser game cheat-proof, but it bounds a fake score by real playing time
 * (the duration itself is checked against a server-signed start time).
 */
export function checkRun(run: RunStats): "implausible_run" | null {
  const { score, distance, coins, durationMs } = run;
  const allInts = [score, distance, coins, durationMs].every(
    (n) => Number.isSafeInteger(n) && n >= 0,
  );
  if (!allInts || durationMs > MAX_RUN_MS) return "implausible_run";
  if (score !== distance + coins * COIN_VALUE) return "implausible_run";
  if (distance > maxMetersForDuration(durationMs + 1000) * 1.02 + 5) return "implausible_run";
  // coin patterns are at least ~36 m apart and hold at most 8 coins
  if (coins > distance * 0.25 + 10) return "implausible_run";
  return null;
}

/** Validates an untrusted JSON body for POST /api/leaderboard. */
export function parseSubmitRequest(body: unknown): SubmitRequest | null {
  if (typeof body !== "object" || body === null) return null;
  const b = body as Record<string, unknown>;
  const nums = ["score", "distance", "coins", "durationMs"] as const;
  if (!nums.every((k) => typeof b[k] === "number")) return null;
  if (typeof b.playerId !== "string" || typeof b.name !== "string" || typeof b.token !== "string") {
    return null;
  }
  return {
    playerId: b.playerId,
    name: b.name,
    token: b.token,
    score: b.score as number,
    distance: b.distance as number,
    coins: b.coins as number,
    durationMs: b.durationMs as number,
  };
}
